# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c4ee2d3cfff3c38f90f7141286778901412002781ed85807613bd7fcf6dac74d72b069a0ba8cb6ad684fdaf411474febdef21ad1e7563599c3d1c1a11d76422

test:
  secret_key_base: 9c54e42707f8664a87e003270bef3df345435e1213a917ded523f144dd49a138c1ed6f0d030c1bea1510b39eb72200ac9e21acade9c54876fd28abf3c06425ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
